### ISSUE TITLE
Dudas generales

### ISSUE THREAD

**Issue by AdanRL** [ULL-ESIT-DSI-1920/dsi1920#1]
Hola @ManzDev   estoy un poco perdido con esta práctica,  hay que seguir los pasos que muestras en el video o intentar hacerlo de otra manera? y otra cosa, las imagenes estoy viendo que es una plantilla con todos los personajes, las recorto a mano para que ocupen 128x128 y las guardo en assets y las modifico con css?

**Comment by ManzDev** [comment]
Hola Adan,

Supongo que te refieres a la práctica 5 (WebComponents) ¿no?

Es correcto. Recortalas en 128x128 y las colocas en assets. Así podrás utilizarlas desde CSS o desde HTML. Vete haciendo la práctica, haces un push con lo que tengas y si tienes dudas me vas preguntando en los issues y te voy orientando.

Saludos,
